package com.oss.domain;

/**
 * OrderItem generated by hbm2java
 */
public class OrderedItem  {
      
     private Integer workStationId;
     private Integer orderItemId;
     private Integer OrderNumber;
     private String status;
     private Integer quantity;
     private Double price;
     private String itemDescription;
     private String toping1;
     private String toping2;
     private String toping3;

     public OrderedItem() {
     }

	public Integer getWorkStationId() {
		return workStationId;
	}

	public void setWorkStationId(Integer workStationId) {
		this.workStationId = workStationId;
	}

	public Integer getOrderItemId() {
		return orderItemId;
	}

	public void setOrderItemId(Integer orderItemId) {
		this.orderItemId = orderItemId;
	}

	public Integer getOrderNumber() {
		return OrderNumber;
	}

	public void setOrderNumber(Integer orderNumber) {
		OrderNumber = orderNumber;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Integer getQuantity() {
		return quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public Double getPrice() {
		return price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public String getItemDescription() {
		return itemDescription;
	}

	public void setItemDescription(String itemDescription) {
		this.itemDescription = itemDescription;
	}

	public String getToping1() {
		return toping1;
	}

	public void setToping1(String toping1) {
		this.toping1 = toping1;
	}

	public String getToping2() {
		return toping2;
	}

	public void setToping2(String toping2) {
		this.toping2 = toping2;
	}

	public String getToping3() {
		return toping3;
	}

	public void setToping3(String toping3) {
		this.toping3 = toping3;
	}

}


