package hcl.model;
// Generated Jul 25, 2020 1:27:08 PM by Hibernate Tools 4.3.1

import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


	
     private int empId;
     private String empName;

    public Employee() {
    }

    public Employee(int empId, String empName) {
       this.empId = empId;
       this.empName = empName;
    }
   
    public int getEmpId() {
        return this.empId;
    }
    
    public void setEmpId(int empId) {
        this.empId = empId;
    }
    public String getEmpName() {
        return this.empName;
    }
    
    public void setEmpName(String empName) {
        this.empName = empName;
    }




}


