package hcl.model;
// Generated Jul 25, 2020 1:27:08 PM by Hibernate Tools 4.3.1



/**
 * Item generated by hbm2java
 */
public class Item  implements java.io.Serializable {


     private int itemId;
     private Cateogory cateogory;
     private String itemName;

    public Item() {
    }

    public Item(int itemId, Cateogory cateogory, String itemName) {
       this.itemId = itemId;
       this.cateogory = cateogory;
       this.itemName = itemName;
    }
   
    public int getItemId() {
        return this.itemId;
    }
    
    public void setItemId(int itemId) {
        this.itemId = itemId;
    }
    public Cateogory getCateogory() {
        return this.cateogory;
    }
    
    public void setCateogory(Cateogory cateogory) {
        this.cateogory = cateogory;
    }
    public String getItemName() {
        return this.itemName;
    }
    
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }




}


