package hcl.model;
// Generated Jul 25, 2020 1:27:08 PM by Hibernate Tools 4.3.1



/**
 * OrderItem generated by hbm2java
 */
public class OrderItem  implements java.io.Serializable {


     private OrderItemId id;
     private Order order;
     private WorkStation workStation;
     private String status;
     private Integer quantity;
     private Integer price;
     private Integer toping1;

    public OrderItem() {
    }

	
    public OrderItem(OrderItemId id, Order order, String status) {
        this.id = id;
        this.order = order;
        this.status = status;
    }
    public OrderItem(OrderItemId id, Order order, WorkStation workStation, String status, Integer quantity, Integer price, Integer toping1) {
       this.id = id;
       this.order = order;
       this.workStation = workStation;
       this.status = status;
       this.quantity = quantity;
       this.price = price;
       this.toping1 = toping1;
    }
   
    public OrderItemId getId() {
        return this.id;
    }
    
    public void setId(OrderItemId id) {
        this.id = id;
    }
    public Order getOrder() {
        return this.order;
    }
    
    public void setOrder(Order order) {
        this.order = order;
    }
    public WorkStation getWorkStation() {
        return this.workStation;
    }
    
    public void setWorkStation(WorkStation workStation) {
        this.workStation = workStation;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public Integer getPrice() {
        return this.price;
    }
    
    public void setPrice(Integer price) {
        this.price = price;
    }
    public Integer getToping1() {
        return this.toping1;
    }
    
    public void setToping1(Integer toping1) {
        this.toping1 = toping1;
    }




}


