package com.oss.echo.model;
// Generated Jul 25, 2020 1:27:08 PM by Hibernate Tools 4.3.1

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;

/**
 * Item generated by hbm2java
 */

@Entity
public class Item  implements java.io.Serializable {

	@Id
	@GeneratedValue
	@Column(name = "item_id")	
	private int itemId;
	private String itemName;
	
	@OneToOne(cascade = CascadeType.ALL)
	@JoinColumn(name = "categoryId")
	private Cateogory cateogory;

	

	public Item() {
	}

	public Item(int itemId, String itemName) {
		this.itemId = itemId;
	
		this.itemName = itemName;
	}

	public int getItemId() {
		return this.itemId;
	}

	public void setItemId(int itemId) {
		this.itemId = itemId;
	}

	public String getItemName() {
		return this.itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public Cateogory getCateogory() {
		return cateogory;
	}

	public void setCateogory(Cateogory cateogory) {
		this.cateogory = cateogory;
	}


}


