package com.oss.echo.model;
// Generated Jul 25, 2020 1:27:08 PM by Hibernate Tools 4.3.1

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;

/**
 * OrderItem generated by hbm2java
 */

@Entity
public class OrderItem  implements java.io.Serializable {


	@Id
	@GeneratedValue
	@Column(name = "order_item_id")	
	private int orderIdItem;
	

	@ManyToOne(cascade = CascadeType.ALL)
	@JoinColumn(name = "order_id")
	private Order order;
	
	@OneToOne(cascade = CascadeType.ALL)
	@JoinColumn(name = "work_station_id")
	private WorkStation workStation;
	private String status;
	private Integer quantity;
	private Integer price;
	private Integer toping1;

	public OrderItem() {
	}


	public OrderItem(int id, Order order, String status) {
		this.orderIdItem = id;
		this.order = order;
		this.status = status;
	}
	public OrderItem(int id, Order order, WorkStation workStation, String status, Integer quantity, Integer price, Integer toping1) {
		this.orderIdItem = id;
		this.order = order;
		this.workStation = workStation;
		this.status = status;
		this.quantity = quantity;
		this.price = price;
		this.toping1 = toping1;
	}


	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}
	public WorkStation getWorkStation() {
		return this.workStation;
	}

	public void setWorkStation(WorkStation workStation) {
		this.workStation = workStation;
	}
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}
	public Integer getPrice() {
		return this.price;
	}

	public void setPrice(Integer price) {
		this.price = price;
	}
	public Integer getToping1() {
		return this.toping1;
	}

	public void setToping1(Integer toping1) {
		this.toping1 = toping1;
	}

	public int getOrderIdItem() {
		return orderIdItem;
	}


	public void setOrderIdItem(int orderIdItem) {
		this.orderIdItem = orderIdItem;
	}




}


