package com.oss.echo.model;
// Generated Jul 25, 2020 1:27:08 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * WorkStation generated by hbm2java
 */

@Entity
public class WorkStation  implements java.io.Serializable {

	@Id
	@GeneratedValue
	@Column(name = "work_station_id")	
	private int workStationId;
	private String name;
	
	public WorkStation() {
	}


	public WorkStation(int workStationId, String name) {
		this.workStationId = workStationId;
		this.name = name;
	}
	public WorkStation(int workStationId, Cateogory cateogory, String name, Set<OrderItem> orderItems) {
		this.workStationId = workStationId;
		this.name = name;
		
	}

	public int getWorkStationId() {
		return this.workStationId;
	}

	public void setWorkStationId(int workStationId) {
		this.workStationId = workStationId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}
	





}


